default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USERNAME") { "your_username" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "your_password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

development:
  <<: *default
  database: pokedex_development

test:
  <<: *default
  database: pokedex_test

production:
  <<: *default
  database: pokedex_production
  username: pokedex
  password: <%= ENV['POKEDEX_DATABASE_PASSWORD'] %>
